version: '3.7'
services:
  postgres:
    container_name: app_database
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}
    ports:
      - "${PG_ADMIN_PORT}:80"
    depends_on:
      - postgres
  
  manager:
    container_name: golang_manager
    build: .
    env_file:
      - .env
    ports:
     - "${APP_PORT}:8081"
    restart: always
    volumes:
      - .:/app
    depends_on: 
      - postgres
    networks:
      - network

volumes:
  db-data:
    driver: local

networks:
  network:
    driver: bridge