version: '3.7'
services:
  app:
    container_name: golang_app
    build: .
    env_file:
      - .env
    ports:
     - "${APP_PORT}:8080"
    restart: always
    volumes:
      - .:/app
    networks:
      - manager_network

networks:
  manager_network:
    external: true