version: '3.7'
services:
  app:
    container_name: golang_app
    build: .
    env_file:
      - .env
    ports:
     - "${APP_PORT}:8080"
    restart: always
    volumes:
      - .:/app
    depends_on: 
      - postgres
    networks:
      - network

volumes:
  db-data:
    driver: local

networks:
  network:
    driver: bridge